pub fn parse(name: String) -> String {
    match name.as_str() {
        "1AT" => String::from("o1"),
        "1BT" => String::from("o2"),
        "1CT" => String::from("o3"),
        "1DT" => String::from("o4"),
        "1ET" => String::from("o5"),
        "1LO" => String::from("o6"),
        "2AT" => String::from("o7"),
        "2BT" => String::from("o8"),
        "2CT" => String::from("o9"),
        "2DT" => String::from("o10"),
        "2LA" => String::from("o11"),
        "3AS" => String::from("o12"),
        "3BS" => String::from("o13"),
        "3CS" => String::from("o14"),
        "3DS" => String::from("o15"),
        "3LAS" => String::from("o16"),
        "3AG" => String::from("o17"),
        "3BG" => String::from("o18"),
        "3CG" => String::from("o19"),
        "3DG" => String::from("o20"),
        "3LAG" => String::from("o21"),
        "4AT" => String::from("o22"),
        "4BT" => String::from("o23"),
        "4CT" => String::from("o24"),
        "4DT" => String::from("o25"),
        "4ET" => String::from("o26"),
        "1LAS" => String::from("o27"),
        _ => String::from("None"),
    }
}