// This looks very bad
pub fn parse(name: String) -> String {
    match name.as_str() {
        "1AT" => String::from("o1"),
        "1BT" => String::from("o2"),
        "1CT" => String::from("o3"),
        "1DT" => String::from("o4"),
        "1ET" => String::from("o5"),
        "1FT" => String::from("o6"),
        "1GT" => String::from("o7"),
        "1LOA" => String::from("o8"),
        "1LOB" => String::from("o9"),
        "2AT" => String::from("o10"),
        "2BT" => String::from("o11"),
        "2CT" => String::from("o12"),
        "2DT" => String::from("o13"),
        "2ET" => String::from("o14"),
        "2LO" => String::from("o15"),
        "3AT" => String::from("o16"),
        "3BT" => String::from("o17"),
        "3CT" => String::from("o18"),
        "3DT" => String::from("o19"),
        "3LA" => String::from("o20"),
        "3AG" => String::from("o20"),
        "4AS" => String::from("o21"),
        "4BS" => String::from("o22"),
        "4CS" => String::from("o23"),
        "4DS" => String::from("o24"),
        "4LAS" => String::from("o25"),
        "4AG" => String::from("o26"),
        "4BG" => String::from("o27"),
        "4CG" => String::from("o28"),
        "4DG" => String::from("o29"),
        _ => String::from("None"),
    }
}
